# Generated by Django 3.0.3 on 2020-02-13 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church_leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_fname', models.CharField(max_length=20)),
                ('leader_lname', models.CharField(max_length=20)),
                ('leader_contact', models.CharField(max_length=20)),
                ('leader_AdmYear', models.IntegerField(verbose_name='Year Of Admission')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_name', models.CharField(max_length=20)),
                ('dpt_role', models.CharField(max_length=500)),
                ('dpt_inspiration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('description', models.CharField(max_length=500)),
                ('image_link', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='Publication Date')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(choices=[('Emeralds', 'Emeralds'), ('Heralds', 'Heralds'), ('Humble', 'Humble'), ('Aroma', 'Aroma'), ('Pilgrims', 'Pilgrims'), ('Royals', 'Royals'), ('Eagles', 'Eagles')], max_length=20)),
                ('inspiration', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='visitor_word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Church_leader')),
            ],
        ),
        migrations.CreateModel(
            name='Scripture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scripture_title', models.CharField(max_length=30)),
                ('scripture_content', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Church_leader')),
            ],
        ),
        migrations.CreateModel(
            name='OtherBussiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_title', models.CharField(max_length=30)),
                ('other_description', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Church_leader')),
            ],
        ),
        migrations.CreateModel(
            name='Leaders_Family_Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_role', models.CharField(choices=[('Head Of Department', 'hod'), ('Assistant Head', 'hod1'), ('Second Assistant', 'hod2'), ('Third Assistant', 'hod3')], default='Family', max_length=30)),
                ('fam_role', models.CharField(choices=[('Family Mom', 'mom'), ('Family Dad', 'dad')], default='Child', max_length=30)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Department')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Family')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Church_leader')),
            ],
        ),
        migrations.CreateModel(
            name='EventsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('detail_name', models.CharField(max_length=30)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='family_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Family'),
        ),
        migrations.CreateModel(
            name='elder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.BooleanField(verbose_name='Is Elder On Duty')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Church_leader')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_title', models.CharField(max_length=30)),
                ('ann_description', models.CharField(max_length=500)),
                ('ann_due_date', models.DateTimeField(verbose_name='Due Date')),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('ann_classification', models.CharField(max_length=30)),
                ('ann_specification', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Church_leader')),
            ],
        ),
    ]
