# Generated by Django 3.0.3 on 2020-02-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church_leader',
            old_name='leader_fname',
            new_name='leader_first_name',
        ),
        migrations.RenameField(
            model_name='church_leader',
            old_name='leader_lname',
            new_name='leader_surname',
        ),
    ]
