# Generated by Django 3.0.3 on 2020-02-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0002_auto_20200213_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church_leader',
            old_name='leader_first_name',
            new_name='leader_fname',
        ),
        migrations.RenameField(
            model_name='church_leader',
            old_name='leader_surname',
            new_name='leader_lname',
        ),
    ]
