# Generated by Django 3.0.3 on 2020-02-17 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0003_auto_20200213_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaders_Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_role', models.CharField(choices=[('hod', 'Head Of Department'), ('hod1', 'Assistant Head'), ('hod2', 'Second Assistant'), ('hod3', 'Third Assistant')], default='Family', max_length=30)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Department')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Church_leader')),
            ],
        ),
        migrations.CreateModel(
            name='Leaders_Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam_role', models.CharField(choices=[('mom', 'Family Mom'), ('dad', 'Family Dad'), ('Child', 'Child')], default='Child', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='family',
            name='inspiration',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Leaders_Family_Department',
        ),
        migrations.AddField(
            model_name='leaders_family',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Family'),
        ),
        migrations.AddField(
            model_name='leaders_family',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Church_leader'),
        ),
    ]
