# Generated by Django 3.0.3 on 2020-03-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0004_auto_20200217_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='ann_classification',
            new_name='announcement_classification',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='ann_description',
            new_name='announcement_description',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='ann_due_date',
            new_name='announcement_due_date',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='ann_specification',
            new_name='announcement_specification',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='ann_title',
            new_name='announcement_title',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='pub_date',
            new_name='publication_date',
        ),
        migrations.RenameField(
            model_name='church_leader',
            old_name='leader_AdmYear',
            new_name='leader_Adm_Year',
        ),
        migrations.RenameField(
            model_name='church_leader',
            old_name='leader_fname',
            new_name='leader_first_name',
        ),
        migrations.RenameField(
            model_name='church_leader',
            old_name='leader_lname',
            new_name='leader_last_name',
        ),
    ]
