# Generated by Django 3.0.3 on 2020-03-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0005_auto_20200325_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dpt_inspiration',
            new_name='department_inspiration',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dpt_name',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dpt_role',
            new_name='department_role',
        ),
    ]
