# Generated by Django 3.0.3 on 2020-03-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0006_auto_20200326_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripture',
            name='attached_verses',
            field=models.CharField(default='phillipians', max_length=30),
            preserve_default=False,
        ),
    ]
