# Generated by Django 3.0.3 on 2020-03-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0007_scripture_attached_verses'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripture',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='active', max_length=20),
            preserve_default=False,
        ),
    ]
