# Generated by Django 3.0.3 on 2020-04-14 05:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0008_auto_20200413_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sda.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 5, 39, 35, 79646, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AddField(
            model_name='sermons',
            name='sermon_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 5, 39, 35, 84633, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 5, 39, 35, 81641, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='church_member',
            name='is_leader',
            field=models.BooleanField(verbose_name='Is The Church Member A Leader?'),
        ),
        migrations.AlterField(
            model_name='elder',
            name='duty',
            field=models.BooleanField(verbose_name='Is Elder On Duty?'),
        ),
        migrations.AlterField(
            model_name='elder',
            name='is_working',
            field=models.BooleanField(verbose_name='Is Elder Active?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 5, 39, 35, 82638, tzinfo=utc), verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 5, 39, 35, 87624, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='otherbussiness',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 5, 39, 35, 85630, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='scripture',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 5, 39, 35, 81641, tzinfo=utc), verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='sermons',
            name='sermon_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 5, 39, 35, 83635, tzinfo=utc), verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='visitor_word',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 5, 39, 35, 84633, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(verbose_name='Is This Comment Visible?')),
                ('comment', models.TextField()),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Church_Member')),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Sermons')),
            ],
        ),
    ]
