# Generated by Django 3.0.3 on 2020-03-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0009_auto_20200330_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='otherbussiness',
            name='other_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scripture',
            name='scripture_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visitor_word',
            name='content',
            field=models.TextField(),
        ),
    ]
