# Generated by Django 3.0.3 on 2020-03-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0010_auto_20200330_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=50),
        ),
    ]
