# Generated by Django 3.0.3 on 2020-04-15 10:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0010_auto_20200414_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=50)),
                ('name_explain', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=14)),
                ('timing', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time Published')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.BooleanField(default=False, verbose_name='Is Viewed?')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time Published')),
            ],
            options={
                'verbose_name_plural': 'Personal Contacts',
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('due_date', models.DateTimeField(blank=True, verbose_name='Due Date')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication Date')),
                ('is_sabbath', models.BooleanField(verbose_name='Is it On Sabbath')),
            ],
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='sermons',
            options={'verbose_name_plural': 'Sermons'},
        ),
        migrations.AlterField(
            model_name='about',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='department',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='otherbussiness',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='scripture',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='sermons',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='services',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='visitor_word',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Department_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Members Welfare', 'Members Welfare'), ('Internal Activities', 'Internal Activities'), ('Church Affairs', 'Church Affairs'), ('Ministry & Outreach', 'Ministry & Outreach')], max_length=50)),
                ('department_role', models.CharField(max_length=500)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('category_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sda.Church_Member')),
            ],
            options={
                'verbose_name': "Department's Category",
                'verbose_name_plural': "Departments' Categories",
            },
        ),
    ]
