# Generated by Django 3.0.3 on 2020-03-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0011_auto_20200330_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=60)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='elder',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='Is Elder Active'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elder',
            name='short_sharing',
            field=models.TextField(default='God Is Good'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='family_name',
            field=models.CharField(choices=[('Emeralds', 'Emeralds'), ('Heralds', 'Heralds'), ('Humble', 'Humble'), ('Aroma', 'Aroma'), ('Pilgrims', 'Pilgrims'), ('Royals', 'Royals'), ('Eagles', 'Eagles'), ('All', 'All')], max_length=20),
        ),
    ]
