# Generated by Django 3.0.3 on 2020-03-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0012_auto_20200330_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
