# Generated by Django 3.0.3 on 2020-04-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0012_auto_20200415_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department_category',
            old_name='department_role',
            new_name='Category_role',
        ),
    ]
