# Generated by Django 3.0.3 on 2020-03-30 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0013_auto_20200330_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 15, 18, 42, 478014, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
