# Generated by Django 3.0.3 on 2020-04-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0013_auto_20200415_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='church_member',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profiles'),
        ),
    ]
