# Generated by Django 3.0.3 on 2020-04-15 14:29

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0014_church_member_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_category',
            field = models.CharField(choices=[('Members Welfare', 'Members Welfare'), ('Internal Activities', 'Internal Activities'), ('Church Affairs', 'Church Affairs'), ('Ministry & Outreach', 'Ministry & Outreach')], max_length=50)
        ),
    ]
