# Generated by Django 3.0.3 on 2020-04-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0016_auto_20200416_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='department_category',
            name='Word_From_The_Leader',
            field=models.TextField(blank=True),
        ),
    ]
