# Generated by Django 3.0.3 on 2020-04-02 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0017_auto_20200402_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsdetail',
            name='detail_name',
        ),
        migrations.AddField(
            model_name='eventsdetail',
            name='detail',
            field=models.CharField(default='Guest', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 11, 36, 8, 326600, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 11, 36, 8, 328595, tzinfo=utc), verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 11, 36, 8, 330589, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='otherbussiness',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 11, 36, 8, 329592, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='scripture',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 11, 36, 8, 327598, tzinfo=utc), verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='visitor_word',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 11, 36, 8, 328595, tzinfo=utc), verbose_name='date published'),
        ),
    ]
