# Generated by Django 3.0.3 on 2020-04-02 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sda', '0018_auto_20200402_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsdetail',
            name='sub_title',
            field=models.CharField(default='guest', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 11, 42, 20, 35188, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 11, 42, 20, 37183, tzinfo=utc), verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 11, 42, 20, 39177, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='otherbussiness',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 11, 42, 20, 38180, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='scripture',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 11, 42, 20, 36186, tzinfo=utc), verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='visitor_word',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 11, 42, 20, 37183, tzinfo=utc), verbose_name='date published'),
        ),
    ]
